# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='position')),
                ('show', models.BooleanField(default=True, verbose_name='show')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='name')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateField(auto_now=True, verbose_name='modified')),
            ],
            options={
                'verbose_name_plural': 'Cities',
                'verbose_name': 'City',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='position')),
                ('show', models.BooleanField(default=True, verbose_name='show')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='name')),
                ('address', models.TextField(blank=True, null=True, verbose_name='address')),
                ('url', models.CharField(blank=True, max_length=250, null=True, verbose_name='link')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateField(auto_now=True, verbose_name='modified')),
                ('city', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='retail.City')),
            ],
            options={
                'verbose_name_plural': 'Partners',
                'verbose_name': 'Partner',
                'ordering': ['pos'],
            },
        ),
    ]
