# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-13 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0003_partner_frontpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='frontpage',
            field=models.BooleanField(default=False, help_text='Show on front page', verbose_name='frontpage'),
        ),
    ]
