# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0004_auto_20170813_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(default='city', help_text='http://hamsabala.ru/slug/slug', verbose_name='slug'),
            preserve_default=False,
        ),
    ]
