# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-14 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retail', '0005_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='frontpage',
            field=models.BooleanField(default=False, help_text='Show on front page', verbose_name='frontpage'),
        ),
    ]
