# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-28 17:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='position')),
                ('show', models.BooleanField(default=True, verbose_name='show')),
                ('title', models.CharField(max_length=140, verbose_name='name')),
                ('slug', models.SlugField(help_text='http://hamsabala.ru/slug/slug', verbose_name='slug')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateField(auto_now=True, verbose_name='modified')),
                ('img', models.ImageField(blank=True, null=True, upload_to=products.models.collection_path, verbose_name='cover')),
                ('color', models.CharField(help_text='HEX number. 23dvr1 for example.', max_length=6, verbose_name='color')),
            ],
            options={
                'verbose_name_plural': 'collections',
                'verbose_name': 'collection',
                'ordering': ['pos'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='position')),
                ('show', models.BooleanField(default=True, verbose_name='show')),
                ('name', models.CharField(blank=True, max_length=140, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='price')),
                ('img', models.ImageField(blank=True, null=True, upload_to=products.models.collection_path, verbose_name='cover')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateField(auto_now=True, verbose_name='modified')),
                ('collection', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Collection')),
            ],
            options={
                'verbose_name_plural': 'products',
                'verbose_name': 'product',
                'ordering': ['collection', 'pos'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField(default=0, verbose_name='position')),
                ('show', models.BooleanField(default=True, verbose_name='show')),
                ('title', models.CharField(max_length=140, verbose_name='name')),
                ('slug', models.SlugField(help_text='http://hamsabala.ru/slug/slug', verbose_name='slug')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateField(auto_now=True, verbose_name='modified')),
                ('img', models.ImageField(blank=True, null=True, upload_to=products.models.section_path, verbose_name='cover')),
            ],
            options={
                'verbose_name_plural': 'sections',
                'verbose_name': 'section',
                'ordering': ['pos'],
            },
        ),
        migrations.AddField(
            model_name='collection',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Section'),
        ),
    ]
