# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-29 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='section',
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.Section'),
        ),
    ]
